name: update
on:
  push:
    branches: ["main"]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: wget
        run: wget https://az764295.vo.msecnd.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/VSCodeUserSetup-x64-1.80.1.exe
      - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: ./VSCodeUserSetup-x64-1.80.1.exe
